# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20170301_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='city',
            field=models.CharField(max_length=50),
        ),
    ]
